use crate::ModType;
use crate::effect::planning::{Poe2ConflictKey, Poe2EffectPhase, Poe2SelectionKey};
use crate::poe2_condition::Poe2Condition;
use crate::poe2_scaling::Poe2Scaling;
use crate::repoe_parse::{GenerationType, HashedTagWeight, ItemClass, Properties, Requirements};
use ahash::AHasher;
use ahash::HashSet;
use exile_core::game::{Game, ModifierDefinitionIdentity};
use std::hash::{Hash, Hasher};

pub fn hash_string(s: &str) -> u64 {
    let mut hasher = AHasher::default();
    s.hash(&mut hasher);
    hasher.finish()
}

pub struct Poe2;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ItemRarity {
    Normal,
    Magic,
    Rare,
    Unique,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum EquipSlot {
    MainHand,
    OffHand,
    BodyArmour,
    Helmet,
    Gloves,
    Boots,
    Amulet,
    Ring1,
    Ring2,
    Belt,
    None,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum Poe2StatModifierKind {
    Plain,
    Conditional(Poe2Condition),
    Scaled(Poe2Scaling),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum StatBucket {
    AbyssalWastingEffectIncreasePrecent,
    AccuracyRating,
    AccuracyRatingIncreaseWithBowPrecent,
    AccuracyRatingPercent,
    AddPowerChargeOnCriticalStrikeIncreasePrecent,
    AdditionalBallistaTotemsAllowed,
    AdditionalBaseCriticalStrikeChance,
    AdditionalBlockChanceAgainstProjectilesIncreasePrecent,
    AdditionalBlockIncreasePrecent,
    AdditionalComboGainChanceIncreasePrecent,
    AdditionalInfusionGainChanceIncreasePrecent,
    AdditionalMaximumBlockIncreasePrecent,
    AdditionalMaximumInfusionStacks,
    AdditionalPhysicalDamageReductionIncreasePrecent,
    AggravateBleedingOlderThanMsOnHit,
    AilmentChanceIncreasePrecent,
    AilmentEffectIncreasePrecent,
    AilmentThresholdFlat,
    AilmentThresholdFromMaximumEnergyShieldPercent,
    AilmentThresholdPercent,
    AllElementalResistanceMax,
    AllSkillGemLevelIncrease,
    AlliesInPresenceAccuracyRating,
    AlliesInPresenceAttackChaosMax,
    AlliesInPresenceAttackChaosMin,
    AlliesInPresenceAttackColdMax,
    AlliesInPresenceAttackColdMin,
    AlliesInPresenceAttackFireMax,
    AlliesInPresenceAttackFireMin,
    AlliesInPresenceAttackLightningMax,
    AlliesInPresenceAttackLightningMin,
    AlliesInPresenceAttackPhysicalMax,
    AlliesInPresenceAttackPhysicalMin,
    AlliesInPresenceAttackSpeedIncreasePrecent,
    AlliesInPresenceCastSpeedIncreasePrecent,
    AlliesInPresenceCriticalStrikeChanceIncreasePrecent,
    AlliesInPresenceCriticalStrikeMultiplierIncrease,
    AlliesInPresenceDamageIncreasePrecent,
    AlliesInPresenceLifeRegenPerMinute,
    AlliesInPresenceResistAllElementsIncreasePrecent,
    ApplyAnaemiaMagnitudeOnHit,
    ApplyBlindOnHitWhileRubySapphireSocketed,
    ApplyDebilitateOnHitWhileEmeraldSapphireSocketed,
    ApplyExposureOnHitWhileRubyEmeraldSocketed,
    ArcaneSurgeEffectOnSelfIncreasePrecent,
    ArchonDelayExpiresXPercentFaster,
    ArchonDurationIncreasePrecent,
    ArchonEffectOnYouIncreasePrecent,
    Armour,
    ArmourAppliesToElementalDamage,
    ArmourBreakAmountIncreasePrecent,
    ArmourBreakDurationIncreasePrecent,
    ArmourBreakEqualToPhysicalDamageDealtOnCriticalStrikeWithSpells,
    ArmourBreakPhysicalDamageIncreasePrecent,
    ArmourPercent,
    ArmourPercentAppliesToChaosDamage,
    ArrowSpeedAdditiveModifiersAlsoApplyToBowDamage,
    AttackAddedChaosDamageIncreasePrecent,
    AttackAddedColdDamageIncreasePrecent,
    AttackAddedFireDamageIncreasePrecent,
    AttackAddedLightningDamageIncreasePrecent,
    AttackAddedPhysicalDamageIncreasePrecent,
    AttackAndCastSpeedIncreasePrecent,
    AttackAndCastSpeedIncreasePrecentDuringFlaskEffect,
    AttackAreaOfEffectIncreasePrecent,
    AttackAreaOfEffectIncreasePrecentPer10Int,
    AttackCriticalStrikeChanceIncreasePrecent,
    AttackCriticalStrikeMultiplierIncrease,
    AttackCriticalStrikeMultiplierIncreasePrecent,
    AttackDamageIncreasePrecent,
    AttackDamageIncreasePrecentWhenOnLowLife,
    AttackMaximumAddedChaosDamage,
    AttackMinimumAddedChaosDamage,
    AttackNumberOfAdditionalChains,
    AttackSkillGemLevelIncrease,
    AttackSkillsHaveAddedLightningDamageEqualToPrecentOfMaximumMana,
    AttackSpeedIncreasePrecentIfNotBeenHitRecently,
    AttackSpeedIncreasePrecentWhenOnFullLife,
    AttackSpeedIncreasePrecentWhileInPresenceOfCompanion,
    AttackSpeedIncreasePrecentWhileMissingWard,
    AttackSpeedPercent,
    AuraEffectIncreasePrecent,
    AvoidAllElementalStatusPrecent,
    AxeAttackSpeedIncreasePrecent,
    AxeDamageIncreasePrecent,
    BannerAreaOfEffectIncreasePrecent,
    BannerDurationIncreasePrecent,
    BaseAllAilmentDurationPrecent,
    BaseArrowSpeedIncreasePrecent,
    BaseAttackSkillCostEfficiencyPrecent,
    BaseAvoidChillPrecent,
    BaseAvoidFreezePrecent,
    BaseAvoidIgnitePrecent,
    BaseAvoidShockPrecent,
    BaseAvoidStunPrecent,
    BaseBleedChanceIsPoisonChanceInstead,
    BaseBleedDurationIncreasePrecent,
    BaseBleedingEffectPercent,
    BaseCastSpeedIncreasePrecent,
    BaseChanceToDazeIncreasePrecent,
    BaseChanceToInflictBleeding,
    BaseChanceToPierce,
    BaseChanceToPoisonOnHitIncreasePrecent,
    BaseChanceToShockPrecent,
    BaseCooldownSpeedIncreasePrecent,
    BaseCriticalStrikeMultiplierIncreasePrecent,
    BaseCurseDurationIncreasePrecent,
    BaseDamageRemovedFromManaBeforeLifePercent,
    BaseDamageTakenIncreasePrecent,
    BaseDamagingAilmentEffectPrecent,
    BaseDebuffSlowMagnitudeIncreasePrecent,
    BaseDeflectionRatingPercentOfArmour,
    BaseElementalStatusAilmentDurationPrecent,
    BaseEnemyCriticalStrikeChancePrecent,
    BaseIgniteDurationDecreasePrecent,
    BaseIgniteIncereasedMagnitudePrecent,
    BaseItemFoundRarityIncreasePrecent,
    BaseLifeCostEfficiencyPrecent,
    BaseLifeGainedOnEnemyDeath,
    BaseLifeGainedOnEnemyHit,
    BaseLifeLeechAmountIncreasePrecent,
    BaseLifeLeechDoesNotStopAtFullLife,
    BaseLifeLeechFromPhysicalAttackDamage,
    BaseLifeLeechRatePrecent,
    BaseManaCostEfficiencyPrecent,
    BaseManaCostPrecent,
    BaseManaGainedOnEnemyDeath,
    BaseManaGainedOnEnemyHit,
    BaseManaLeechAmountIncreasePrecent,
    BaseManaLeechFromPhysicalAttackDamage,
    BaseManaLeechRatePrecent,
    BaseManaReservationEfficiencyPrecent,
    BaseMaximumSealsForSkill,
    BaseMinionDurationPrecent,
    BaseNumberOfCrossbowBolts,
    BaseNumberOfEssenceSpiritsAllowed,
    BaseOnlsaughtOnHitPrecent,
    BasePoisonChanceIsBleedChanceInstead,
    BasePoisonDurationIncreasePrecent,
    BasePoisonEffectIncreasePrecent,
    BaseProjectileSpeedIncreasePrecent,
    BaseRageCostEfficiencyPrecent,
    BaseReservationEfficiencyPrecent,
    BaseSelfChillDurationDecreasePrecent,
    BaseSelfFreezeDurationDecreasePrecent,
    BaseSelfShockDurationDecreasePrecent,
    BaseSkillAreaOfEffectIncreasePrecent,
    BaseSkillCostEfficiencyPrecent,
    BaseSkillCostLifeInsteadOfManaIncreasePrecent,
    BaseSlowPotencyPercent,
    BaseSpellCooldownSpeedPrecent,
    BaseSpellCriticalStrikeMultiplierIncreasePrecent,
    BaseSpellManaCostEfficiencyPrecent,
    BaseSpiritReservationEfficiencyPrecent,
    BaseThornsCriticalStrikeChance,
    BaseUnholyMightGrantedMagnitudePrecent,
    BellHitLimit,
    BleedChancePrecent,
    BlindEffectIncreasePrecent,
    Block,
    BlockChanceIncreasePrecent,
    BlockDamageTakenWhileActiveBlockingPrecent,
    BodyArmourEvasionRatingPrecent,
    BodyArmourPrecent,
    BowAttackSpeedIncreasePrecent,
    BowDamageIncreasePrecent,
    BrokenArmourAndSunderedArmourDebuffEffectPrecent,
    CannotBeInflictedByCorruptedBlood,
    CannotBePoisoned,
    CannotDie,
    CastSpeedPrecentDuringManaFlaskEffect,
    CastSpeedPrecentPerNumUniqueSpellsCastRecently,
    CastSpeedPrecentWhenOnFullLife,
    CastSpeedPrecentWhenOnLowLife,
    CastSpeedPrecentWhileOnFullMana,
    ChanceBleedOnHitWithAttacks,
    ChanceToBlindOnHitWithAttacks,
    ChanceToCrushOnHitPrecent,
    ChanceToFire1AdditionalProjectileWithRolloverPrecent,
    ChanceToFire1AdditionalProjectileWithRolloverWithBowAttacks,
    ChanceToForkExtraProjectileIncreasePrecent,
    ChanceToGainArchonOfNatureOnOvergrowingPlantPrecent,
    ChanceToGainArchonOfUndeathWhenYouCreateAnOfferingPrecent,
    ChanceToGainPowerChargeOnStunPrecent,
    ChanceToInflictIncisionOnAttackHitIncreasePrecent,
    ChanceToNotConsumeExertedAttack,
    ChanceToNotConsumeInfusionPrecentIfLostArchonInPast6Seconds,
    ChanceToPoisonOnHitWithAttacks,
    ChanceToRetain40PrecentOfGloryOnUsePrecent,
    ChaosDamageIncreasePrecent,
    ChaosDamagePercent,
    ChaosDamageResistancePrecentPerPoisonStack,
    ChaosDamageTakenOverTimePrecent,
    ChaosDotMultiplierPrecent,
    ChaosResistance,
    ChaosResistanceMax,
    ChaosResistancePrecentWhileUsingFlask,
    ChaosSpellSkillGemLevelIncrease,
    ChargeSkipConsumeChancePrecent,
    CharmChargesGainedIncreasePrecent,
    CharmChargesReducedUsedIncreasePrecent,
    CharmDurationIncreasePrecent,
    CharmGainXGuardForDuration,
    CharmRecoverXLifeWhenUsed,
    CharmRecoverXManaWhenUsed,
    CharmsPrecentChanceToNotConsumeCharges,
    ChillDurationIncreasePrecent,
    ColdDamageIncreasePrecent,
    ColdDamagePrecentColdInfusionCollectedLast8Seconds,
    ColdDamageTakenPrecentGoesToLifeOver4Seconds,
    ColdDotMultiplierPrecent,
    ColdResistance,
    ColdResistanceMax,
    ColdResistancePenetration,
    ColdSpellSkillGemLevelIncrease,
    CompanionAttackSpeedPrecent,
    CompanionDamageIncreasePrecent,
    CompanionMaximumLifeIncreasePrecent,
    CorruptedSkillGemLevelIncrease,
    CreatedRemnantsPrecentChanceToDuplicatePickUpResults,
    CriticalHitDamageBonusPrecentVsEnemiesWithin2mDistance,
    CriticalHitDamagingAilmentEffectIncreasePrecent,
    CriticalStrikeChanceIncreasePrecent,
    CriticalStrikeChancePrecentVsEnemiesFurtherThan6mDistance,
    CriticalStrikeChancePrecentVsMarkedEnemies,
    CrossbowAttackSpeedIncreasePrecent,
    CrossbowDamageIncreasePrecent,
    CrossbowReloadInstantChanceIncreasePrecent,
    CurseAreaOfEffectIncreasePrecent,
    CurseDelayIncreasePrecent,
    CurseEffectIncreasePrecent,
    CurseEffectOnSelfPrecent,
    DaggerAttackSpeedIncreasePrecent,
    DaggerCriticalStrikeChanceIncreasePrecent,
    DaggerDamageIncreasePrecent,
    DamageAgainstEnemiesWithFullyBrokenArmourIncreasePrecent,
    DamageIfYouHaveConsumedACorpseRecentlyIncreasePrecent,
    DamageIncreasePrecent,
    DamagePrecentAgainstEnemiesMarkedByYou,
    DamagePrecentPerPoisonUpTo75,
    DamagePrecentVsImmobilisedEnemies,
    DamagePrecentWhileInPresenceOfCompanion,
    DamagePrecentWhileLeeching,
    DamagePrecentWhileTotemActive,
    DamageRemovedFromSpectresBeforeLifeOrEsPrecent,
    DamageTakenGoesToLifeManaEsOver4SecondsPrecent,
    DamageTakenGoesToLifeOver4Seconds,
    DamageTakenGoesToLifeOver4SecondsIncreasePrecent,
    DamageTakenGoesToMana,
    DamageToRareAndUniqueEnemiesIncreasePrecent,
    DamageVsCursedEnemiesPerEnemyCursePrecent,
    DamageWhileUsingCharmIncreasePrecent,
    DamageWithBowSkillsIncreasePrecent,
    DamageWithHeraldSkillsIncreasePrecent,
    DamagingAilmentDurationIncreasePrecent,
    DamagingAilmentsDealDamageIncreasePrecent,
    Deal1000ChaosDamagePerSecondFor10SecondsOnHit,
    DebuffTimePassedIncreasePrecent,
    DeflectDamageTaken,
    DeflectedHitDamageTakenPrecentRecoupedAsLife,
    DeflectionRatingPrecent,
    Dexterity,
    DexterityAndIntelligencePrecent,
    DexterityPercent,
    DodgeRollBaseTravelDistance,
    DummyStatDisplayNothing,
    ElementalAilmentTypesApplyDamageTakenPrecent,
    ElementalDamageIncreasePrecent,
    ElementalDamageWithAttackSkillsIncreasePrecent,
    ElementalPenetrationPrecentDuringFlaskEffect,
    ElementalSkillLimitPrecent,
    EmpoweredAttackDamageIncreasePrecent,
    EnemiesChanceExplodeOnKill,
    EnemiesChaosResistancePrecentWhileCursed,
    EnergyGeneratedIncreasePrecent,
    EnergyShield,
    EnergyShieldDelayDecreasePrecent,
    EnergyShieldFromFocusIncreasePrecent,
    EnergyShieldRechargeRateIncreasePrecent,
    EnergyShieldRechargeRatePrecentIfBlockedRecently,
    EssenceAbyssGuaranteedPick,
    EssenceBuffElementalDamageTakenPrecent,
    EssenceDisplayElementalDamageTakenWhileNotMovingPrecent,
    Evasion,
    EvasionAppliesToDeflection,
    EvasionPercent,
    EvasionRatingPrecent,
    EvasionRatingPrecentWhileLeeching,
    ExplodeBurningEnemiesFor10LifeAsFireOnKillChancePrecent,
    ExplodeEnemiesFor10LifeAsPhysicalOnKillChancePrecent,
    ExplodeEnemiesFor25LifeAsChaosOnKillChancePrecent,
    ExposureEffectPrecent,
    FasterBleedDamage,
    FireDamageIncreasePrecent,
    FireDamagePrecentIfFireInfusionCollectedLast8Seconds,
    FireDamageTakenGoesToLifeOver4SecondsPrecent,
    FireDotMultiplierPrecent,
    FireResistance,
    FireResistanceMax,
    FireResistancePenetration,
    FireSpellAdditionalCriticalStrikeChancePerMyriad,
    FireSpellSkillGemLevelIncrease,
    FishQuantityPrecent,
    FishRarityPrecent,
    FishingHookType,
    FishingLineStrengthPrecent,
    FishingLureType,
    FishingPoolConsumptionPrecent,
    FishingRangePrecent,
    FlailCriticalStrikeChanceIncreasePrecent,
    FlailDamageIncreasePrecent,
    FlaskChargesGainedIncreasePrecent,
    FlaskChargesReducedUsedIncreasePrecent,
    FlaskDurationIncreasePrecent,
    FlaskLifeRecoveryRateIncreasePrecent,
    FlaskManaRecoveryRateIncreasePrecent,
    FlaskRecoveryAmountPercentToRecoverInstantly,
    FlasksPrecentChanceToNotConsumeCharges,
    FreezeThresholdIncreasePrecent,
    FullyBreakEnemiesArmourOnHeavyStunWithShieldSkills,
    GainAlchemistsGeniusOnFlaskUsePrecent,
    GainArcaneSurgeOnCritPrecent,
    GainOnslaughtFor3SecondsPrecent,
    GainXRageOnMeleeHit,
    GainXRageWhenGetByEnemyHit,
    GenerateXChargesForAnyFlaskPerMinute,
    GenerateXChargesForCharmsPerMinute,
    GenerateXChargesForLifeFlasksPerMinute,
    GenerateXChargesForManaFlasksPerMinute,
    GlobalArmourEvasionEnergyShieldPrecent,
    GlobalAttackColdMax,
    GlobalAttackColdMin,
    GlobalAttackFireMax,
    GlobalAttackFireMin,
    GlobalAttackLightningMax,
    GlobalAttackLightningMin,
    GlobalAttackPhysicalMax,
    GlobalAttackPhysicalMin,
    GlobalItemAttributeReducedRequirementsPrecent,
    GlobalSkillGemQualityPluss,
    GloryGenerationIncreasePrecentForBanners,
    GloryGenerationPrecent,
    GoldFromEnemiesIncreasePrecent,
    GrantsGraveCommandSkill,
    GrenadeSkillCooldownCount,
    GrenadeSkillCooldownSpeedIncreasePrecent,
    GrenadeSkillDamagePrecent,
    GrenadeSkillDurationPrecent,
    GrenadeSkillNumberOfAdditionalProjectiles,
    GrenadeSkillPrecentChanceToExplodeTwice,
    HandWrapsAttackDamagePrecentFinalOnLowMana,
    HandWrapsDamageTakenPrecentFinalOnLowLife,
    HandWrapsMoreGlobalEvasionEnergyShield,
    HaveUnholyMight,
    HazardDamageIncreasePrecent,
    HeavyStunPoiseDecayRatePrecent,
    HinderEnemyChaosDamageTakenPrecent,
    HinderEnemyElementalDamageTakenPrecent,
    HinderEnemyPhysicalDamageTakenPrecent,
    HitDamageFreezeMultiplierIncreasePrecent,
    HitDamageFreezeMultiplierPrecentIfConsumedPowerChargeRecently,
    HitDamageImmobilisationMultiplierPrecent,
    HitDamagePinMultiplierIncreasePrecent,
    HitDamageStunMultiplierIncreasePrecent,
    IgniteChanceIncreasePrecent,
    IgniteEffectPrecentIfConsumedEnduranceChargeRecently,
    IgniteShockChillDurationIncreasePrecent,
    IncreaseEvasionPercentArmourPercentEnergyShieldPercentFromShield,
    Intelligence,
    IntelligencePercent,
    InvocationSkillMaximumEnergyPrecent,
    InvocationSpellChanceToCostHalfEnergyPrecent,
    InvocationSpellDamagePrecent,
    KnockbackDistanceIncreasePrecent,
    LeechPrecentIsInstant,
    Life,
    LifeFlaskChargesGainedIncreasePrecent,
    LifeGainedOnAttackHitIfCritRecently,
    LifeGainedOnAttackHitVsCursedEnemies,
    LifeGainedOnBlock,
    LifeLeechCanOvercapLife,
    LifePercent,
    LifeRegenPerMinutePercent,
    LifeRegenerationPerMinutePrecentWhileFrozen,
    LifeRegenerationRateIncreasePrecent,
    LifeRegenerationRatePrecentWhileMoving,
    LifeRegenerationRatePrecentWhileUsingLifeFlask,
    LiferRegenPerMinute,
    LightRadiusIncreasePrecent,
    LightningDamageCanIgnite,
    LightningDamageIncreasePrecent,
    LightningDamagePrecentIfLightningInfusionCollectedLast8Seconds,
    LightningDamageTakenGoesToLifeOver4SecondsPrecent,
    LightningResistance,
    LightningResistanceMax,
    LightningResistancePenetration,
    LightningSpellSkillGemLevelIncrease,
    MaceDamageIncreasePrecent,
    MaceHitDamageStunMultiplierIncreasePrecent,
    Mana,
    ManaCostEfficiencyPrecentIfDodgeRolledRecently,
    ManaFlaskChargesGainedIncreasePrecent,
    ManaGainedOnAttackHitVsCursedEnemies,
    ManaGainedOnBlock,
    ManaPercent,
    ManaPrecentGainedOnBlock,
    ManaPrecentToGainAsArmour,
    ManaRegenerationRatePercent,
    ManaRegenerationRatePrecentWhileShocked,
    ManaRegenerationRatePrecentWhileStationary,
    ManaReservationEfficiencyPrecentPer1,
    MarkEffectIncreasePrecent,
    MarkSkillDurationIncreasePrecent,
    MarkSkillGemLevels,
    MarkUseSpeedIncreasePrecent,
    MarkedEnemyTakesIncreasedDamage,
    MaxEnduranceCharges,
    MaxFortificationPer5,
    MaxFrenzyCharges,
    MaxPowerCharges,
    MaxPuppetMasterStacksPer5,
    MaximumAddedColdDamagePerFrenzyCharge,
    MaximumAddedFireDamageIfBlockedRecently,
    MaximumEnergyShieldFromBodyArmourPrecent,
    MaximumEnergyShieldPercent,
    MaximumManaGainedOnKillPercent,
    MaximumRage,
    MaximumWardPrecent,
    MeleeAttackSkillsAdditionalTotemsAllowed,
    MeleeAttacksNumberOfAdditionalProjectiles,
    MeleeDamageIncreasePrecent,
    MeleeDamageIncreasePrecentIfYouveDealtProjectileAttackHitRecently,
    MeleeSkillGemLevelIncrease,
    MinimumAddedColdDamagePerFrenzyCharge,
    MinimumAddedFireDamageIfBlockedRecently,
    MinionAccuracyRatingIncreasePrecent,
    MinionAdditionalPhysicalDamageReductionIncreasePrecent,
    MinionAreaOfEffectPrecent,
    MinionArmourBreakPhysicalDamagePrecent,
    MinionAttackAndCastSpeedIncreasePrecent,
    MinionBaseDamagingAilmentEffectPrecent,
    MinionChanceToFire1AdditionalProjectilePrecent,
    MinionChaosResistance,
    MinionChaosResistanceIncreasePrecent,
    MinionColdResistance,
    MinionCriticalStrikeChanceIncreasePrecent,
    MinionCriticalStrikeMultiplierIncreasePrecent,
    MinionDamageIncreasePrecent,
    MinionFireResistance,
    MinionLightningResistance,
    MinionMaximumLifeIncreasePrecent,
    MinionResummonSpeedIncreasePrecent,
    MinionSkillAreaOfEffectIncreasePrecent,
    MinionSkillGemLevelIncrease,
    MovementSpeedPenaltyReductionPercent,
    MovementSpeedPercent,
    NonSkillBaseAllDamageToGainAsChaos,
    NonSkillBaseAllDamageToGainAsCold,
    NonSkillBaseAllDamageToGainAsFire,
    NonSkillBaseAllDamageToGainAsLightning,
    OfferingDurationIncreasePrecent,
    OfferingLifeIncreasePrecent,
    ParryDamageIncreasePrecent,
    ParrySkillEffectDurationIncreasePrecent,
    ParryStunThresholdIncreasePrecentDuringParry,
    PercentEvasionRatingAsExtraArmour,
    PhysicalDamageIncreasePrecent,
    PhysicalDamageReductionPrecent,
    PhysicalSpellSkillGemLevelIncrease,
    PlacingTrapsCooldownRecoveryForThrowingIncreasePrecent,
    PresenceAreaIncreasePrecent,
    ProjectileAttackRangePrecent,
    ProjectileChanceToChain1ExtraTimeFromTerrainIncreasePrecent,
    ProjectileDamageIncreasePrecent,
    ProjectileDamageIncreasePrecentIfYouveDealtMeleeHitRecently,
    ProjectileSkillGemLevelIncrease,
    ProjectileSpeedIncreasePrecentForCrossbowSkills,
    QuarterstaffAttackSpeedIncreasePrecent,
    QuarterstaffDamageIncreasePrecent,
    QuarterstaffHitDamageFreezeMultiplierIncreasePrecent,
    QuiverModEffectIncreasePrecent,
    RecoverMaximumLifeOnKillIncreasePrecent,
    ReduceBaseAllAilmentDurationOnSelfPrecent,
    ReduceCriticalStrikeMultiplierToSelf,
    ReducedAttackManaCostPrecent,
    ReducedAttributeRequirementsPercent,
    ReloadSpeedIncreasePrecent,
    SelfBleedDurationDecreasePrecent,
    SelfPoisonDurationDecreasePrecent,
    SelfStatusAilmentDurationReductionPercent,
    ShockChanceIncreasePrecent,
    ShockDurationIncreasePrecent,
    ShockEffectIncreasePrecent,
    SkillEffectDurationIncreasePrecent,
    SkillSpeedIncreasePrecent,
    SpearAttackSpeedIncreasePrecent,
    SpearCriticalStrikeMultiplierIncreasePrecent,
    SpearDamageIncreasePrecent,
    SpellCriticalStrikeChanceIncreasePrecent,
    SpellDamageIncreasePrecent,
    SpellPhysicalDamageIncreasePrecent,
    SpellSkillGemLevelIncrease,
    SpellsCostLifeInsteadOfMana,
    Spirit,
    Strength,
    StrengthPercent,
    StrikesDealMeleeSplash,
    StunThreshold,
    StunThresholdFromMaximumEnergyShieldPercent,
    StunThresholdPercent,
    StunThresholdWhenNotStunnedRecentlyPercent,
    SummonTotemCastSpeedIncreasePrecent,
    SwordAttackSpeedIncreasePrecent,
    SwordDamageIncreasePrecent,
    ThornsDamageIncreasePrecent,
    ThornsPhysicalMax,
    ThornsPhysicalMin,
    TotemDamageIncreasePrecent,
    TotemLifeIncreasePrecent,
    TrapCriticalStrikeChanceIncreasePrecent,
    TrapCriticalStrikeMultiplierIncrease,
    TrapDamageIncreasePrecent,
    TrapSkillGemLevelIncrease,
    TrapThrowingSpeedIncreasePrecent,
    TrapTriggerRadiusIncreasePrecent,
    TriggeredSpellSpellDamageIncreasePrecent,
    UnarmedAttackSpeedIncreasePrecent,
    UnarmedDamageIncreasePrecent,
    VolatilityOnKillChanceIncreasePrecent,
    WarCryEmpowersNextXMeleeAttacks,
    WarcryBuffEffectIncreasePrecent,
    WarcryCooldownSpeedIncreasePrecent,
    WarcryDamageIncreasePrecent,
    WarcrySpeedIncreasePrecent,
    Ward,
    WardRegenerationRateIncreasePrecent,
    WeaponSwapSpeedIncreasePrecent,
    WitheredMagnitudeIncreasePrecent,
}

pub fn stat_id_to_bucket(stat_id: &str) -> Option<StatBucket> {
    match stat_id {
        "chaos_damage_+%" => Some(StatBucket::ChaosDamagePercent),
        "additional_strength" => Some(StatBucket::Strength),

        _ => None,
    }
}

pub fn classify_bucket(tags: &[String]) -> Option<StatBucket> {
    const RULES: &[(&str, StatBucket)] = &[
        ("fire_resistance", StatBucket::FireResistance),
        ("cold_resistance", StatBucket::ColdResistance),
        ("lightning_resistance", StatBucket::LightningResistance),
        ("chaos_resistance", StatBucket::ChaosResistance),
        ("energy_shield", StatBucket::EnergyShield),
        ("life", StatBucket::Life),
        ("mana", StatBucket::Mana),
        ("armour", StatBucket::Armour),
        ("evasion", StatBucket::Evasion),
        ("block", StatBucket::Block),
    ];
    RULES
        .iter()
        .find(|(tag, _)| tags.iter().any(|t| t == tag))
        .map(|(_, b)| *b)
}

#[derive(Debug, Clone)]
pub struct Poe2ItemState {
    pub item_level: u16,
    pub quality: u16,
    pub rarity: ItemRarity,
    pub is_corrupted: bool,

    pub base_name: String,
    pub drop_level: u16,
    pub properties: Properties,
    pub requirements: Option<Requirements>,
    pub tags: HashSet<u64>,
    pub equip_slot: EquipSlot,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Copy)]
pub struct Poe2ModifierId(pub u64);

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ModOrigin {
    Crafted,
    Fractured,
    Rune,
    Dropped,
    Corrupted,
}

#[derive(Debug, Clone)]
pub struct Poe2ModifierStat {
    pub id_hash: u64,
    pub min: i64,
    pub max: i64,
    pub is_local: bool,
    pub kind: Poe2StatModifierKind,
    pub phase: Poe2EffectPhase,
    pub buckets: Vec<StatBucket>,
    pub conflict_key: Option<Poe2ConflictKey>,
    pub selection_key: Option<Poe2SelectionKey>,
}

#[derive(Debug, Clone)]
pub struct Poe2ModifierDefinition {
    pub id: Poe2ModifierId,
    pub kind: ModType,
    pub required_level: u16,
    pub stats: Vec<Poe2ModifierStat>,
    pub groups: Vec<u64>,
    pub spawn_weights: Vec<HashedTagWeight>,
    pub generation_type: GenerationType,
}

impl ModifierDefinitionIdentity for Poe2ModifierDefinition {
    type Id = Poe2ModifierId;
    fn modifier_definition_id(&self) -> Self::Id {
        self.id
    }
}

#[derive(Debug, Clone)]
pub struct Poe2ModifierInstance {
    pub rolls: Vec<i64>,
    pub origin: ModOrigin,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Copy)]
pub enum Poe2Effect {
    GlobalStat {
        id: u64,
        value: i64,
        mod_type: ModType,
    },
    LocalStat {
        slot: EquipSlot,
        id: u64,
        value: i64,
        mod_type: ModType,
    },
    ScaledStat {
        target_id: u64,
        multiplier: i64,
        scaling: Poe2Scaling,
        mod_type: ModType,
    },
}

impl Game for Poe2 {
    type ItemBase = ItemClass;
    type ItemState = Poe2ItemState;
    type ModifierDefinitionId = Poe2ModifierId;
    type ModifierDefinition = Poe2ModifierDefinition;

    type ModifierInstance = Poe2ModifierInstance;

    type Effect = Poe2Effect;
    type EffectCondition = Poe2Condition;
    type EffectSourceId = String;
}
